{% set name = "ultranest" %}
{% set version = "4.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dfebdc4b2bc0138238f65e8f957b70fe296cb094c895172f4a368e792a59b501

build:
  number: 0
  # may need to later add "skip: True  # [win]" to disable Windows.
  script_env:
    - MPLBACKEND=agg
  skip: true  # [py<30 or python_impl == "pypy"]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    # cython project, so need a compiler
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cython
    - numpy
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
    - pytest-runner

  run:
    - python
    - numpy
    - matplotlib-base
    - corner
    - six
    - cython
    - scipy
    - getdist

test:
  imports:
    - ultranest
  source_files:
    - tests/*
  requires:
    - cython
    - pandas
    - h5py
    - joblib
    - pytest
    - git
    - pytest-html
    - pip

about:
  home: https://johannesbuchner.github.io/UltraNest/
  license: AGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Fit and compare complex models reliably and rapidly. Advanced Nested Sampling.

  description: |
    When scientific models are compared to data, two tasks are important: 1) contraining the model parameters and 2) comparing the model to other models. Different techniques have been developed to explore model parameter spaces. This package implements a Monte Carlo technique called nested sampling.
    Nested sampling allows Bayesian inference on arbitrary user-defined likelihoods. In particular, posterior probability distributions on model parameters are constructed, and the marginal likelihood (“evidence”) Z is computed. The former can be used to describe the parameter constraints of the data, the latter can be used for model comparison (via Bayes factors) as a measure of the prediction parsimony of a model.
    In the last decade, multiple variants of nested sampling have been developed. These differ in how nested sampling finds better and better fits while respecting the priors (constrained likelihood prior sampling techniques), and whether it is allowed to go back to worse fits and explore the parameter space more.
    This package develops novel, advanced techniques for both (See https://johannesbuchner.github.io/UltraNest/method.html). They are especially remarkable for being free of tuning parameters and theoretically justified. Beyond that, UltraNest has support for Big Data sets and high-performance computing applications.
    UltraNest is intended for fitting complex physical models with slow likelihood evaluations, with one to hundreds of parameters. UltraNest intends to replace heuristic methods like multi-ellipsoid nested sampling and dynamic nested sampling with more rigorous methods. UltraNest also attempts to provide feature parity compared to other packages (such as MultiNest).
  doc_url: https://johannesbuchner.github.io/UltraNest/
  dev_url: https://github.com/JohannesBuchner/UltraNest

extra:
  recipe-maintainers:
    - JohannesBuchner
